# Generated by Django 5.0.6 on 2024-05-10 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
