# Generated by Django 5.0.6 on 2024-05-10 18:35

import uuid

from django.db import migrations


def create_uuid(apps, schema_editor):
    CustomUser = apps.get_model('app_accounts', 'CustomUser')
    for user in CustomUser.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0002_customuser_uuid'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
    ]
